name: restaurant_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  http: ^1.6.0
  google_fonts: ^8.0.0
  sqflite: ^2.3.2
  path: ^1.9.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.0.0
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
